[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'nn-rag'
dynamic = ['version', 'dependencies']
description = 'Neural Retrieval-Augmented Generation for GitHub code blocks'
readme = { file = 'README.md', content-type = 'text/markdown' }
license = { file = 'LICENSE' }
keywords = ['retrieval-augmented generation', 'RAG', 'large language model', 'LLM', 'code blocks', 'neural retrieval', 'generation pipeline', 'vector search', 'indexing', 'Python', 'faiss', 'block extraction', 'GitHub code', 'contextual embedding']

requires-python = '>=3.6'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Topic :: Software Development :: Libraries',
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    'Topic :: Text Processing :: Natural Language',
    'Topic :: Machine Learning,
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research'    
]
authors = [{ name = 'ABrain One and contributors', email = 'AI@ABrain.one' }]

[project.urls]
Homepage = 'https://ABrain.one'
Repository = 'https://github.com/ABrain-One/nn-rag'
'Bug Tracker' = 'https://github.com/ABrain-One/nn-rag/issues'

[tool.setuptools.dynamic]
version = { file = 'version' }
dependencies = { file = 'requirements.txt' }

[tool.setuptools.packages.find]
where = ['']

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
'ab' = ['*.json']
'*' = ['requirements.txt', 'LICENSE', 'version', '*.md']
